version: '3.4'

services:
  dd-agent:
    image: datadog/dogstatsd:latest
    ports:
      - "8125:8125/udp"
    environment:
      - DD_SEND_HOST_METADATA=false
    env_file:
      - ./dd_api_key.env
    networks:
      - datadog

networks:
  datadog:
