version: '3.4'

services:
  dd-agent:
    image: datadog/agent:latest
    ports:
      - "8125:8125/udp"
      - "8126:8126"
    environment:
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
      - "DD_DOGSTATSD_TAGS=tagkey:test"
    env_file:
      - ./dd_api_key.env
    networks:
      - datadog

networks:
  datadog:
